site_name: PDS Laboratories
site_description: Laboratory material for the PDS course
strict: true

theme:
  name: mkdocs
  locale: en
  highlightjs: true

nav:
  - Home: index.md
  - Lab 1 Docker fundamentals: lab-01.md

markdown_extensions:
  - fenced_code
  - toc:
      permalink: true
